Feat/redux
sievertknorrblad/rijact pull request #4
Opened 2018-05-31 08:14 UTC by sievertknorrblad

2018-05-31 11:25 UTC, iamstarkov requested changes
needs some work

2018-05-31 11:25 UTC, iamstarkov commented on src/components/header/index.js
> +    <button onClick={e => toggleTheme()}>toggle the theme</button>
do you know if you are using toggleTheme from props or imported one?

2018-05-31 11:25 UTC, iamstarkov commented on src/components/header/index.js
> +    <button onClick={e => toggleTheme()}>toggle the theme</button>
its called variable overshadowing

2018-05-31 11:25 UTC, iamstarkov commented on src/components/header/index.js
> +    <button onClick={e => toggleTheme()}>toggle the theme</button>
do this `import * as actions from '../../actions'` as I specified in the gist https://gist.github.com/iamstarkov/45c4fd7d9cc99b943b277995ad2f9f71#5-structuring-redux-related-code

2018-05-31 11:25 UTC, iamstarkov commented on src/actions/index.js
> +  export { requestItemStart, requestItemSuccess, requestItemsIdsFailure, requestItemsIdsStart, requestItemsIdsSuccess, requestItemFailure, toggleTheme, updateItemsToShow };
you dont need to have all of these, just export every action and action creator on its own

2018-05-31 11:25 UTC, iamstarkov commented on src/components/newsItem/index.js
> +import { fetchItem as fetchItemAction } from '../../actions';
fix this as I mentioned before

2018-05-31 11:25 UTC, iamstarkov commented on src/components/newsItem/index.js
> +    return this.props.item !== nextProps.item
what is your intention here?

2018-05-31 11:25 UTC, iamstarkov commented on src/components/newsItemList/index.js
> +import { default as NewsItem } from '../newsItem';
nope, refer to components from components index file: `import { NewsItem } from '../'`

2018-05-31 11:25 UTC, iamstarkov commented on src/components/pageNewsList/index.js
>  import { NewsItemList } from '../newsItemList';
and here

2018-05-31 11:25 UTC, iamstarkov commented on src/index.js
> +                document.getElementById('root'));
you have a bit odd indentation here, but its fine

2018-05-31 11:25 UTC, iamstarkov commented on src/components/index.js
> +export { default as PageNewsList } from './pageNewsList';
like you changed what you export to consume here in the. so please import from this file, not point to specific component folder

2018-05-31 11:26 UTC, iamstarkov commented on src/components/newsItem/index.js
> +    return this.props.item !== nextProps.item
I mean
```
> {} === {}
false
```

2018-05-31 12:07 UTC, sievertknorrblad commented on src/components/newsItem/index.js
> +    return this.props.item !== nextProps.item
Can probably be removed right? We always want to re-render if we get new data in the state for this id?

2018-05-31 12:15 UTC, sievertknorrblad commented on src/index.js
> +                document.getElementById('root'));
Didn't know what else to do :P The 2 arguments passed should be aligned, and <App /> should be indented under <Provider> right :)?

2018-05-31 13:39 UTC, iamstarkov commented on src/components/newsItem/index.js
> +    return this.props.item !== nextProps.item
yes, we can remove it

2018-05-31 13:43 UTC, iamstarkov approved these changes
some minor comments, otherwise looks really good

2018-05-31 13:43 UTC, iamstarkov commented on src/components/newsItemList/index.js
> +import { NewsItem } from '../../components';
how about `from '../'`?

2018-06-07 00:22 UTC, iamstarkov approved these changes
LGTM

2018-06-11 09:07 UTC, merged